version: "3"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_SCHEMA=iis
  app:
    build:
      context: .
    container_name: iis
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?currentSchema=iis
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin