version: "3"

services:
  postgres:
    image: postgres:15
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    container_name: iis
    ports:
      - 8080:8080
    depends_on:
      - postgres
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata: