spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/iis?currentSchema=iis
    username: postgres
    password: admin
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: NON_NULL
  liquibase:
    change-log: classpath:db/changelog/db.changelog-root.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: hfbvhfabvkhefbvhrbvvrheferhfbcenvfdvbfavjfdvlafjdbvjfdbvjfnvjkdsncjk
  expiration:
    access: 5
    refresh: 30