spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/iis?currentSchema=iis
    username: postgres
    password: admin
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: NON_NULL
  liquibase:
    change-log: classpath:db/db.changelog-root.yaml

mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: hfbvhfabvkhefbvhrbvvrheferhfbcenvfdvbfavjfdvlafjdbvjfdbvjfnvjkdsncjk
  access: 5
  refresh: 30

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html