spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_HOST}:5432/postgres
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: NON_NULL
  liquibase:
    change-log: classpath:db/db.changelog-root.yaml

mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: ${JWT_SECRET}
  access: 5
  refresh: 30
