spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/iis
    username: postgres
    password: admin
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: NON_NULL
