spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: NON_NULL
  liquibase:
    change-log: classpath:db/db.changelog-root.yaml
  config:
    import: optional:file:.env

mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: ${JWT_SECRET}
  access: 5
  refresh: 30
