apiVersion: apps/v1
kind: Deployment
metadata:
  name: iis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iis
  template:
    metadata:
      labels:
        app: iis
    spec:
      containers:
        - name: iis
          image: hizmailovich/iis@sha256:8ba8bee31b126a9bc661db9b42d1c49320d429376b37a3617dabea999cac28bb
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_USER
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_PASSWORD
            - name: DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: iis-secrets
                  key: JWT_SECRET